apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-database-uri-secret
type: Opaque
data:
  {{- $url := printf "postgresql://%s:%s@%s-postgresql/%s" .Values.app_vars.DATABASE_USER .Values.app_vars.DATABASE_PASSWORD .Values.app_vars.DATABASE_HOSTNAME .Values.app_vars.DATABASE_NAME}}
  DATABASE_URI: {{ $url | b64enc | quote }}