FROM python:3.7

WORKDIR /opt/app

COPY app.py app.py

COPY requirements.txt requirements.txt

RUN ls /opt/app

RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 80

CMD ["python3", "/opt/app/app.py"]